---
version: 2
jobs:
  build:
    working_directory: /cli
    docker:
      - image: node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v2-yarn-{{ .Branch }}
            - v2-yarn-master
      - run: yarn
      - run: yarn test --coverage
      - run: curl -s https://codecov.io/bash | bash
      - save_cache:
          key: v2-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /cli/node_modules
            - /usr/local/share/.cache/yarn
