---
version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v1-yarn-{{ .Branch }}
            - v1-yarn-master
      - run: git submodule sync && git submodule update --init --recursive --remote
      - run: yarn
      - run: |
          npx jest --coverage --runInBand
          bash <(curl -s https://codecov.io/bash)
      - run: {command: "./bin/run version", when: always}
      - run: {command: "npx eslint .", when: always}
      - run: {command: "npx flow check", when: always}
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /tmp/cli-engine/node_modules
            - /tmp/cli-engine/npm-packages-offline-cache
            - /tmp/cli-engine/yarn
            - /usr/local/share/.cache/yarn
